import numpy as np
import matplotlib.pyplot as plt
import yaml
import gmsh
import pandas as pd
import os


def dat_to_dataframe(dat_file): # from pyelmer.post import dat_to_dataframe
    """Read a .dat file generated by elmer (e.g. SaveData/SaveScalars
    solver) into a pandas dataframe.

    Args:
        dat_file (str): file path of elmer .dat file

    Returns:
        pandas.core.frame.DataFrame: content of dat file with header
    """
    with open(f"{dat_file}.names") as f:
        lines = f.readlines()
    names = []
    names_start = False
    for line in lines:
        if names_start == True:
            names.append(":".join(line.split(":")[1:]).strip())
        if (
            "Data on different columns" in line
            or "Variables in columns of matrix" in line
        ):
            names_start = True
    return pd.read_table(dat_file, names=names, sep='\s+')



def monotonically_ordered(array):
    """This function takes an array as input and returns a new array where the rows are sorted based on the first element of each row

    Args:
        array (float): 

    Returns:
        
    """
    #return sorted(array, key=lambda x: x[0])
    return np.array(sorted(array, key=lambda x: x[0]))


#--------------------------------------bottom part of the crystal  ------------------------------------#



def get_crystal_melt_interface(file_location):
    """
    returns the crystal melt interphase monotonically_ordered (from larger y-axis to smaller)
    Args:
        file_location (str): file path of 2-D boundary .dat file


    Returns:
        2D array of (x,y) of the interface line between crystal and melt
    """
    df = dat_to_dataframe(file_location)
    df_crystal_finalstep = df.loc[df["Call count"] == df["Call count"][df.index[-1]]] # last iteration
    coords_crystal = np.array(
    [
        df_crystal_finalstep["coordinate 1"].to_numpy(),
        df_crystal_finalstep["coordinate 2"].to_numpy(),
        df_crystal_finalstep["temperature"].to_numpy()
    ])

    newarray =np.column_stack((coords_crystal[0,:], coords_crystal[1,:]))

    return monotonically_ordered(newarray)
    #return newarray



                            #--------------------------------------------------------#

def T_bnd_for_3D(file_location,output_location,coord_int):
    """
    Args:
        file_location (str): file path of 2-D boundary .dat file
        output_location (str): file path of 3-D where coupling will be done .dat file
        coord_int (int): interpolation coordinate of the extracted array (x=0,y=1)

    Returns:
        2D array of the thermal boundaries and the coord_int
    """
    df = dat_to_dataframe(file_location)
    df_crystal_finalstep = df.loc[df["Call count"] == df["Call count"][df.index[-1]]] # last iteration
    coords_crystal = np.array(
    [
        df_crystal_finalstep["coordinate 1"].to_numpy(),
        df_crystal_finalstep["coordinate 2"].to_numpy(),
        df_crystal_finalstep["temperature"].to_numpy()
    ])

    newarray =np.column_stack((coords_crystal[coord_int,:], coords_crystal[2,:]))

    # Create a boolean mask for unique rows based on the first column
    mask = np.unique(newarray[:, 0], return_index=True)[1]

    # Use the mask to select only the unique rows
    filtered_data = newarray[mask]

    np.savetxt(output_location +os.path.basename(file_location), monotonically_ordered(filtered_data))

    return print("The file", os.path.basename(file_location), "was createad at :",output_location )


                            #--------------------------------------------------------#



def make_T_files(dir_2D,output_dir):

    crystal_T_boundary_side = dir_2D + '/crystal_T_boundary_side.dat'
    crystal_T_boundary_top = dir_2D + '/crystal_T_boundary_top.dat'
    crystal_T_boundary_bottom = dir_2D + '/phase-if.dat'

    T_bnd_for_3D(crystal_T_boundary_side,output_dir,1)
    T_bnd_for_3D(crystal_T_boundary_top,output_dir,0)
    #T_bnd_for_3D(crystal_T_boundary_bottom,output_dir,0)
    T_bnd_for_3D(crystal_T_boundary_bottom,output_dir,1)
    return print("------------------T files created in 3D folder -----------------")






if __name__ == "__main__":

    dir_2D = './2D-case/simdata/02_crystal_bnd_T/results'
    output_dir = './simdata/04_test_sif/'

    crystal_T_boundary_side = dir_2D + '/crystal_T_boundary_side.dat'
    crystal_T_boundary_top = dir_2D + '/crystal_T_boundary_top.dat'
    crystal_T_boundary_bottom = dir_2D + '/phase-if.dat'

    T_bnd_for_3D(crystal_T_boundary_side,output_dir,1)
    T_bnd_for_3D(crystal_T_boundary_top,output_dir,0)
    T_bnd_for_3D(crystal_T_boundary_bottom,output_dir,0)

