import os 
import numpy as np
import matplotlib.pyplot as plt
import yaml
import pandas as pd

def dat_to_dataframe(dat_file): # from pyelmer.post import dat_to_dataframe
    """Read a .dat file generated by elmer (e.g. SaveData/SaveScalars
    solver) into a pandas dataframe.

    Args:
        dat_file (str): file path of elmer .dat file

    Returns:
        pandas.core.frame.DataFrame: content of dat file with header
    """
    with open(f"{dat_file}.names") as f:
        lines = f.readlines()
    names = []
    names_start = False
    for line in lines:
        if names_start == True:
            names.append(":".join(line.split(":")[1:]).strip())
        if (
            "Data on different columns" in line
            or "Variables in columns of matrix" in line
        ):
            names_start = True
    return pd.read_table(dat_file, names=names, sep='\s+')




def heat_fluxes_to_yaml(sim_dir):
    """defines yml file at results

    Args:
        sim_dir (str): simulation directory
    """
    # write the flux yml file 
    fluxes = {}
    with open(sim_dir + "/boundaries.txt" , 'r') as file:
        bnds = file.readlines()
    df_scalars = dat_to_dataframe(sim_dir +'/results/scalars.dat')
    headers = df_scalars.columns.tolist()
    heat_flux_headers = [header for header in headers if  header.startswith('diffusive flux')]

    for i, line in enumerate(bnds):
        fluxes.update({line.strip(): float(df_scalars[heat_flux_headers].iloc[-1].iloc[i])}) # results from the last iteration
    with open(sim_dir + "/results/heat-fluxes.yml", "w") as f:
        yaml.dump(fluxes, f, sort_keys=False)
    return print("------------- Heat fluxes written in results folder -------------")




def converge_plots(sim_dir, config_elmer):
    """Convergence plots

    Args:
        sim_dir (str): simulation directory
        config_elmer (str): config_elmer yml

    Returns:
        Convergence plots at result folder
    """
    df = dat_to_dataframe(sim_dir + '/results/scalars.dat')
    headers = df.columns.tolist()
    iterations = len(df)

    with open(config_elmer) as f:
        config_elmer = yaml.safe_load(f)
    max_iterations = config_elmer["axisymmetric_steady"]["Steady State Max Iterations"]
    heat_solver_tolerance = config_elmer["HeatSolver"]["Linear System Convergence Tolerance"]

    # Determine which heater power scaling key exists.
    if 'res: heater power scaling 2' in headers:
        scaling_key = 'res: heater power scaling 2'
    elif 'res: heater power scaling 1' in headers:
        scaling_key = 'res: heater power scaling 1'
    else:
        print("------------- No scaling factor at scalars -------------")
        return

    # Plot for body min: temperature mask crystal, if available.
    if 'body min: temperature mask crystal' in headers:
        fig, ax1 = plt.subplots(figsize=(10, 6))

        # Plot minimum crystal temperature
        color = 'blue'
        ax1.set_xlabel('Steady-state Iteration')
        ax1.set_ylabel('Minimum Crystal Temperature (K)', color=color)
        ax1.plot(df.index + 1, df['body min: temperature mask crystal'], color=color, marker='o')
        ax1.tick_params(axis='y', labelcolor=color)

        temp_min = df['body min: temperature mask crystal'].min()
        temp_max = df['body min: temperature mask crystal'].max()
        padding = 2 * (temp_max - temp_min)
        ax1.set_ylim(temp_min - padding, temp_max + padding)
        ax1.get_yaxis().get_major_formatter().set_scientific(False)
        ax1.get_yaxis().get_major_formatter().set_useOffset(False)

        # Create a second y-axis for heater power scaling.
        ax2 = ax1.twinx()
        color = 'black'
        ax2.set_ylabel('Smart Heater Power', color=color)
        ax2.plot(df.index + 1, df[scaling_key], color=color, marker='s')
        ax2.tick_params(axis='y', labelcolor=color)

        scale_min = df[scaling_key].min()
        scale_max = df[scaling_key].max()
        padding = 2 * (scale_max - scale_min)
        ax2.set_ylim(scale_min - padding, scale_max + padding)
        ax2.get_yaxis().get_major_formatter().set_scientific(False)
        ax2.get_yaxis().get_major_formatter().set_useOffset(False)

        text_str = f"Converged at: {iterations} / {max_iterations} iterations"
        props = dict(boxstyle='round', facecolor='white', alpha=0.5)
        ax1.text(0.05, 0.95, text_str, transform=ax1.transAxes, fontsize=12,
                 verticalalignment='top', bbox=props)

        plt.title('Minimum Crystal Temperature and Smart Heater Power vs. Steady-state Iteration')
        plt.xlim(0, iterations + 1)
        fig.tight_layout()
        plt.savefig(sim_dir + '/results/Converge_min_T.png')

    # Plot for body max: vonmises mask crystal, if available.
    if 'body max: vonmises mask crystal' in headers:
        fig, ax1 = plt.subplots(figsize=(10, 6))

        color = 'blue'
        ax1.set_xlabel('Steady-state Iteration')
        ax1.set_ylabel('Max Von Mises at crystal ($MPa$)', color=color)
        ax1.plot(df.index + 1, df['body max: vonmises mask crystal'] / 1e6, color=color, marker='o')
        ax1.tick_params(axis='y', labelcolor=color)

        stress_min = df['body max: vonmises mask crystal'].min() / 1e6
        stress_max = df['body max: vonmises mask crystal'].max() / 1e6
        padding = 2 * (stress_max - stress_min)
        ax1.set_ylim(stress_min - padding, stress_max + padding)
        ax1.get_yaxis().get_major_formatter().set_scientific(False)
        ax1.get_yaxis().get_major_formatter().set_useOffset(False)

        # Second y-axis for heater power scaling.
        ax2 = ax1.twinx()
        color = 'black'
        ax2.set_ylabel('Smart Heater Power', color=color)
        ax2.plot(df.index + 1, df[scaling_key], color=color, marker='s')
        ax2.tick_params(axis='y', labelcolor=color)

        scale_min = df[scaling_key].min()
        scale_max = df[scaling_key].max()
        padding = 2 * (scale_max - scale_min)
        ax2.set_ylim(scale_min - padding, scale_max + padding)
        ax2.get_yaxis().get_major_formatter().set_scientific(False)
        ax2.get_yaxis().get_major_formatter().set_useOffset(False)

        plt.title('Max Von Mises and Smart Heater Power vs. Steady-state Iteration')
        plt.xlim(0, iterations + 1)
        fig.tight_layout()
        plt.savefig(sim_dir + '/results/Converge_vonmises.png')

    return "------------- Convergence plots done -------------"



def converge_interface(sim_dir):
    """Melt/crystal interface deflection plot

    Args:
        sim_dir (str): simulation directory
        melt_y0 (float): Melt height

    Returns:
        Plot at result folder
    """
    phase_if_df = dat_to_dataframe(sim_dir + '/results/phase-if.dat')


    if not os.path.exists(sim_dir + '/results/phase-if.dat'):
        return print("------------- phase-if.dat does not exist. Skipping interface convergence plot -------------")

    # Get unique call counts
    call_counts = phase_if_df['Call count'].unique()

    # Create a color map
    cmap = plt.cm.get_cmap('viridis')  # You can choose a different colormap if you prefer

    # Create the plot
    fig, ax = plt.subplots(figsize=(10, 8))
    
    for i, call_count in enumerate(call_counts):
        subset = phase_if_df[phase_if_df['Call count'] == call_count]
        color = cmap(i / len(call_counts))
        ax.plot(subset['coordinate 1']*1e3, subset['coordinate 2']*1e3, 
                color=color, label=f'Steady-state Iteration {call_count}', 
                marker='o', linestyle='-', markersize=4,alpha = 0.7)

    max_coord1_index = subset['coordinate 1'].idxmax() #find xmax
    melt_y0 = subset.loc[max_coord1_index, 'coordinate 2']


    ax.axhline(y=melt_y0*1e3, color='blue', linestyle='--', label='Melt height')
    y_axis_max_difference = (subset[("coordinate 2")] - melt_y0).abs().max()
    x_middle = (ax.get_xlim()[0] + ax.get_xlim()[1]) / 2

    # Add text in the middle of the horizontal line
    ax.text(x_middle, melt_y0*1e3,  f"Max deflection: {y_axis_max_difference * 1e3:.2f} mm", ha='center', va='bottom', fontsize=10, color='black')

    ax.set_xlabel('Radial position (mm)')
    ax.set_ylabel('Melt/crystal interface deflection (mm)')
    ax.set_title('Melt/crystal interface')
    ax.legend()    
    fig.tight_layout()
    plt.savefig(sim_dir + '/results/Converge_interface_deflection.png')
    return print("------------- Interface convergence plot done -------------")


def induced_power(sim_dir,config_sim):
    """Induced_power plots

    Args:
        sim_dir (str): simulation directory
        config_sim (str): config_sim yml file

    Returns:
        Induced_power plot at result folder
    """
    
    df_scalars = dat_to_dataframe(sim_dir + '/results/scalars.dat')
    headers = df_scalars.columns.tolist()
    Induced_power_headers = [header for header in headers if  header.startswith('body int: joule heating')]

    if not Induced_power_headers:
        return print("------------- Induced power not calculated -------------")

    with open(config_sim) as f:
        config_sim = yaml.safe_load(f)
    frequency = config_sim["heating_induction"]["frequency"]
    initial_current = config_sim["heating_induction"]["current"]


    fig, ax = plt.subplots(figsize=(10, 6))
    # Calculate the values for each bar

    if "res: heater power scaling 2" in df_scalars.columns and len(df_scalars) > 0:
        scaling_factor = df_scalars["res: heater power scaling 2"].iloc[-1]
    else:
        scaling_factor = 1  # if scaling factor =1 means that simulation stars with No smart heater

    values = (df_scalars[Induced_power_headers].iloc[-1] * scaling_factor)/1e3
    total_value = (df_scalars["int: joule heating"].iloc[-1] * scaling_factor)/1e3
    rest_bodies = total_value - values.sum()

    # Add rest_bodies and the total value to the values list
    all_values = list(values) + [rest_bodies, total_value]

    # Create bars including rest_bodies and total
    bars = ax.bar(range(len(all_values)), all_values, align='center')

    # Customize the plot
    bodies = [s.split()[-1] for s in Induced_power_headers] + ['rest bodies', 'total power']
    ax.set_xticks(range(len(all_values)))
    ax.set_xticklabels(bodies, rotation=45, ha='right')

    ax.set_ylabel('Power (kW)')
    ax.set_title('Induced Power')

    # Add value labels on top of each bar
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.3f}',
                ha='center', va='bottom')

    # Highlight the rest_bodies and total bars
    bars[-2].set_color('gray')  # Rest bodies
    bars[-1].set_color('black')  # Total


    text_str = f"Frequency: {frequency/1e3:.1f} kHz\n" \
            f"Initial current: {initial_current:.1f} A\n" \
            f"Current: {initial_current * (scaling_factor)**(1/2):.1f} A"
    props = dict(boxstyle='round', facecolor='white', alpha=0.5)
    ax.text(0.05, 0.95, text_str, transform=ax.transAxes, fontsize=12,
            verticalalignment='top', bbox=props)

    # Adjust layout to prevent cutting off labels
    fig.tight_layout()
    plt.savefig(sim_dir + '/results/Induced_power.png')
    return print("------------- Induced_power plot done -------------")

def evaluate_heat_flux(sim_dir,thermal_conductivity):

    fig = plt.figure(figsize=(8,8))
    
    df = dat_to_dataframe(sim_dir + '/results/crystal_T_boundary_side.dat')
    df = df.loc[df["Call count"] == df["Call count"].max()]
    df = df.drop_duplicates(subset=['Node index'], keep='first').reset_index(drop=True)
    df["coordinate 2"] -= df["coordinate 2"].min()
    # df = df.loc[df["coordinate 2"] <= crys_length*1e-3]
    df.sort_values(["coordinate 2", "coordinate 1"], inplace=True)
    df.reset_index(inplace=True)

    normal_grad = []
    normal_flux = []
    for i in range(len(df)):
        if i < len(df) - 1:
            dx = df.loc[i+1, "coordinate 1"] - df.loc[i, "coordinate 1"]
            dy = df.loc[i+1, "coordinate 2"] - df.loc[i, "coordinate 2"]
        else:
            dx = df.loc[i, "coordinate 1"] - df.loc[i-1, "coordinate 1"]
            dy = df.loc[i, "coordinate 2"] - df.loc[i-1, "coordinate 2"]
        n = np.array([dy, -dx])
        n /= np.linalg.norm(n)
        grad = np.array([df.loc[i, "temperature grad 1"], df.loc[i, "temperature grad 2"]])
        normal_grad.append(np.dot(n, grad))
        normal_flux.append(- np.dot(n, grad) * thermal_conductivity)

    normal_grad = np.array(normal_grad)
    normal_flux = np.array(normal_flux)

    #print(f"Mean heat flux: {normal_flux.mean():.2f} W/m^2")

    plt.plot(df["coordinate 2"][2:-2], normal_flux[2:-2])
    plt.xlabel("crystal heigth")
    plt.ylabel("normal heat flux [W/m^2]")
    plt.grid(linestyle=":")
    fig.tight_layout()

    plt.savefig(sim_dir + '/results/heat_flux_Crystal.png')
    return print("------------- Crystal_heat_flux plot done -------------")


def run_post(sim_dir):

    print("------------- Post Results ------------- ")
    try:
        heat_fluxes_to_yaml(sim_dir)
    except Exception as e:
        print(f"Error in heat_fluxes_to_yaml: {e}")

    try:
        converge_interface(sim_dir)
    except Exception as e:
        print(f"Error in converge_interface: {e}")

    try:
        converge_plots(sim_dir, "config_elmer.yml")
    except Exception as e:
        print(f"Error in converge_plots: {e}")

    try:
        induced_power(sim_dir, "config_elmer.yml")
    except Exception as e:
        print(f"Error in induced_power: {e}")




def csv_for_macplas(sim_dir,name='data_for_macplas'):

    df = dat_to_dataframe(sim_dir + '/results/crystal_T_boundary_side.dat')
    df_crystal_finalstep = df.loc[df["Call count"] == df["Call count"][df.index[-1]]] # last iteration
    df_unique = df_crystal_finalstep.drop_duplicates(subset=['Node index'], keep='first').reset_index(drop=True)
    df_surf  = df_unique.iloc[:, 3:9].copy()
    df_surf ['Boundary'] = 'surface'

    df_surf_sorted = df_surf.sort_values(by='coordinate 2', ascending=True).reset_index(drop=True)


    # Discard first and last point (shared with other boundaries)
    df_surf_sorted = df_surf_sorted.iloc[:-1].reset_index(drop=True)

    df = dat_to_dataframe(sim_dir + '/results/phase-if.dat')
    df_crystal_finalstep = df.loc[df["Call count"] == df["Call count"][df.index[-1]]] # last iteration
    df_unique = df_crystal_finalstep.drop_duplicates(subset=['Node index'], keep='first').reset_index(drop=True)
    df_if  = df_unique.iloc[:, 3:9].copy()
    df_if ['Boundary'] = 'interface'

    df_if_sorted = df_if.sort_values(by='coordinate 1', ascending=True).reset_index(drop=True)


    df = dat_to_dataframe(sim_dir + '/results/crystal_T_boundary_top.dat')
    df_crystal_finalstep = df.loc[df["Call count"] == df["Call count"][df.index[-1]]] # last iteration
    df_unique = df_crystal_finalstep.drop_duplicates(subset=['Node index'], keep='first').reset_index(drop=True)
    df_top  = df_unique.iloc[:, 3:9].copy()
    df_top ['Boundary'] = 'surface'

    df_top_sorted = df_top.sort_values(by='coordinate 1', ascending=False).reset_index(drop=True)
    



    df_all = pd.concat([ df_if_sorted,df_surf_sorted,df_top_sorted], ignore_index=True)
    df_all.loc[df_all["coordinate 1"] < 1e-5, "coordinate 1"] = 0.0 # This makes 0 the first and last point
    

    output_path = sim_dir + '/' + name +'.csv'
    df_all.to_csv(output_path, index=False)





if __name__ == "__main__":
    sim_dir = "./simdata/macplasData/length=0.020_vpull=0.2"

    csv_for_macplas(sim_dir)
    #evaluate_heat_flux(sim_dir,7.7 )
    #heat_fluxes_to_yaml(sim_dir)
    # converge_plots(sim_dir,"config_elmer.yml")
    #converge_interface(sim_dir)
    # induced_power(sim_dir, "config_sim.yml")




